### ISSUE TITLE
Month and year fields allow more than 2 digits

### ISSUE THREAD

**Issue by laurentpellegrino** [morbidick/stripe-elements#4]

**Comment by laurentpellegrino** [comment]
@morbidick The length limit is not applied because of a typo in the `paper-input` attribute: `maxlenght` instead of `maxlength` and the type which could be set to string:

`type="text" pattern="[0-9]*" maxlength="2"`

**Comment by morbidick** [comment]
oh a typo, thx. I think `type=tel` like we use for the card number would be better since it opens the right keyboard on mobile.
