### ISSUE TITLE
hide zip code depending on the users locale

### ISSUE THREAD

**Issue by laurentpellegrino** [morbidick/stripe-elements#5]
I noticed the zip code is optional and can be displayed or not. Unfortunately, there are countries where it does not make sense to display it while in some others it is. It means that in such case, the field must be present and optional. However, users that should not enter a zip code will be confused by the field. I don't know on what _stripe-elements_ relies but it is able to display the field based on the card numbers and/or locale.

**Comment by morbidick** [comment]
i think thats out of the scope of this element, it can be hidden via attribute and should be done by the application.
