### ISSUE TITLE
Default value for `_apiVersion`

### ISSUE THREAD

**Issue by laurentpellegrino** [morbidick/stripe-elements#7]
It's more a question than an issue. I wonder if a future release version of Stripe may invalidate the current API version value that is used and thus make this element silently fail.

**Comment by morbidick** [comment]
The official api docs dont mention the `payment_user_agent` param, i only found it by looking at the original elements requests. I hoped it would bring a little bit more stability to the api endpoint but im not sure if it might even trigger their fraud detection (they are doing a lot of activity tracking on the page which we dont) and if we should change it to something human readable like `github.com/morbidick/stripe-elements` for better debugging on their site.

**Comment by morbidick** [comment]
Since the element displays all returned api errors that contain a message i hope it will never "really silently" fail.

**Comment by morbidick** [comment]
There is a [changelog](https://stripe.com/docs/upgrades#api-changelog). the current version reflects 2017-08-15.

**Comment by morbidick** [comment]
closed after using the official version header
