### ISSUE TITLE
Add method to clear all fields

### ISSUE THREAD

**Issue by laurentpellegrino** [morbidick/stripe-elements#9]
This is useful after form validation to prepare a future update.

**Comment by morbidick** [comment]
we should be able to use the iron-form reset function, ill have a look

**Comment by laurentpellegrino** [comment]
Yep, in my case I have added the following:

```
reset() {
    this.$.form.reset();
}

validate() {
    return this.$.form.validate();
}
```

**Comment by morbidick** [comment]
@lpellegr would you like opening a PR for the reset? And maybe expose a function `basicValidate` or something similar? `validate` itself could be a little bit misleading since we validate on token generation with the Stripe backend.
